### ISSUE TITLE
Button states wrong

### ISSUE THREAD

**Issue by nmeurer** [Skinah/wled#1]
Hey Skinah!
Thank you for your awesome binding! It makes integrating wled so much easier!
I'm new to openhab so I don't know if this is a known issue or not but when I'm trying to turn off my leds with a switch, the switch jumps from off to on, and back while the leds stay off, giving false information. Any idea what could be the issue?
Greetings and keep it up!

**Comment by Skinah** [comment]
Look at the mqtt brokers messages and see if a message is telling openhab to do it. Also upgrade your firmware.

**Comment by nmeurer** [comment]
Thanks, fixed it by setting the QoS to 2
Greetings!
