### ISSUE TITLE
Sync State

### ISSUE THREAD

**Issue by rdu** [Skinah/wled#12]
Is it possible to add a channel for the sync state?
I have multiple led strips. I would like to switch the sync state via openhab rather than via the web client.

Thank you!

**Comment by Skinah** [comment]
Are you on openHAB V3 yet? I have done a lot of work on V3 support that needs testing and any new features will only be for V3 from now on. In the V3 build under going review for merge these changes are done.

+ sync settings
+ segments (partially done)

**Comment by rdu** [comment]
No I am still on 2.5.x.
When I OH3 is released I will migrate, but not for now.

**Comment by rdu** [comment]
I have a working OH3  running now. (for testing)
If you like you can send me a build for testing the new features.

**Comment by Skinah** [comment]
It has been merged so it should be in the daily snapshot builds. A jar is at this link if you don’t want to load the snapshot.

https://github.com/openhab/openhab-addons/pull/8669

**Comment by Skinah** [comment]
Closing as now it’s merged this repo is no longer the most up to date source for this binding.
