### ISSUE TITLE
Unable to install binding

### ISSUE THREAD

**Issue by regnets** [Skinah/wled#2]
If i am unable to install the binding. I copied both jar files into my addons folder however i receive the following message in openhab.log.

2020-01-29 16:25:33.711 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-wled'

I am using openhab 2.5 in a docker container. I exposed the addon folder inside the container (/openhab/addons) to my file system and i can confirm that they are in the right place.

**Comment by Skinah** [comment]
Openhab 2.5 needs a number of reboots for the cache files to be created. Annoying but after a few starts it will work and show up in paper ui. You do not install in paper ui it just appears as already installed after the reboots.

**Comment by regnets** [comment]
Even after 4 restarts of the docker container i can't see any WLED Binding in the Paper UI.

**Comment by Skinah** [comment]
Sorry can’t help, post in openhab forum as it is most likely related to docker. The espmilighthub binding is 90% the same so more users will have experience getting that going so be careful how you title the thread to gain more people to look.

**Comment by regnets** [comment]
OK, now it is showing up. Really strange behaviour. If anybody else experience it, just give it time and some reboots. I don't understand whats change. However today first reboot it showed directly up.
